/**
 * Due to https://github.com/microsoft/TypeScript/issues/30033#issuecomment-792254387
 * VSCode is unable to suggest auto import from libraries in node_modules
 * 
 * Due to https://github.com/microsoft/TypeScript/issues/43034#issuecomment-788668552
 * There is a workaround to forceful index packages
 * 
 * You can freely delete this file, if you are not using VSCode
 */

import {} from '@mtasa/client/function/audio';
import {} from '@mtasa/client/function/blip';
import {} from '@mtasa/client/function/browser';
import {} from '@mtasa/client/function/camera';
import {} from '@mtasa/client/function/clothes_and_body';
import {} from '@mtasa/client/function/collision_shape';
import {} from '@mtasa/client/function/cursor';
import {} from '@mtasa/client/function/drawing';
import {} from '@mtasa/client/function/effects';
import {} from '@mtasa/client/function/element';
import {} from '@mtasa/client/function/engine';
import {} from '@mtasa/client/function/event';
import {} from '@mtasa/client/function/explosion';
import {} from '@mtasa/client/function/file';
import {} from '@mtasa/client/function/fire';
import {} from '@mtasa/client/function/gui';
import {} from '@mtasa/client/function/input';
import {} from '@mtasa/client/function/light';
import {} from '@mtasa/client/function/marker';
import {} from '@mtasa/client/function/object';
import {} from '@mtasa/client/function/output';
import {} from '@mtasa/client/function/ped';
import {} from '@mtasa/client/function/pickup';
import {} from '@mtasa/client/function/player';
import {} from '@mtasa/client/function/projectile';
import {} from '@mtasa/client/function/radar_area';
import {} from '@mtasa/client/function/resource';
import {} from '@mtasa/client/function/searchlight';
import {} from '@mtasa/client/function/server';
import {} from '@mtasa/client/function/team';
import {} from '@mtasa/client/function/utility';
import {} from '@mtasa/client/function/vehicle';
import {} from '@mtasa/client/function/water';
import {} from '@mtasa/client/function/weapon';
import {} from '@mtasa/client/function/weapon_creation';
import {} from '@mtasa/client/function/world';
import {} from '@mtasa/client/function/xml';

import {} from '@mtasa/client/oop/Blip';
import {} from '@mtasa/client/oop/Browser';
import {} from '@mtasa/client/oop/Camera';
import {} from '@mtasa/client/oop/ColShape';
import {} from '@mtasa/client/oop/Effect';
import {} from '@mtasa/client/oop/Element';
import {} from '@mtasa/client/oop/File';
import {} from '@mtasa/client/oop/GuiBrowser';
import {} from '@mtasa/client/oop/GuiCheckBox';
import {} from '@mtasa/client/oop/GuiComboBox';
import {} from '@mtasa/client/oop/GuiEdit';
import {} from '@mtasa/client/oop/GuiElement';
import {} from '@mtasa/client/oop/GuiGridList';
import {} from '@mtasa/client/oop/GuiLabel';
import {} from '@mtasa/client/oop/GuiMemo';
import {} from '@mtasa/client/oop/GuiStaticImage';
import {} from '@mtasa/client/oop/GuiTab';
import {} from '@mtasa/client/oop/GuiTabPanel';
import {} from '@mtasa/client/oop/GuiWindow';
import {} from '@mtasa/client/oop/Light';
import {} from '@mtasa/client/oop/Marker';
import {} from '@mtasa/client/oop/Object';
import {} from '@mtasa/client/oop/Ped';
import {} from '@mtasa/client/oop/Player';
import {} from '@mtasa/client/oop/Projectile';
import {} from '@mtasa/client/oop/RadarArea';
import {} from '@mtasa/client/oop/RenderTarget';
import {} from '@mtasa/client/oop/Resource';
import {} from '@mtasa/client/oop/Searchlight';
import {} from '@mtasa/client/oop/Shader';
import {} from '@mtasa/client/oop/Sound';
import {} from '@mtasa/client/oop/Team';
import {} from '@mtasa/client/oop/Timer';
import {} from '@mtasa/client/oop/Vehicle';
import {} from '@mtasa/client/oop/Water';
import {} from '@mtasa/client/oop/Weapon';
import {} from '@mtasa/client/oop/XML';
import {} from '@mtasa/client/oop/XmlNode';

import {} from '@mtasa/deprecated/blip';
import {} from '@mtasa/deprecated/colshape';
import {} from '@mtasa/deprecated/dx';
import {} from '@mtasa/deprecated/element';
import {} from '@mtasa/deprecated/events';
import {} from '@mtasa/deprecated/marker';
import {} from '@mtasa/deprecated/MTA';
import {} from '@mtasa/deprecated/object';
import {} from '@mtasa/deprecated/ped';
import {} from '@mtasa/deprecated/pickup';
import {} from '@mtasa/deprecated/projectile';
import {} from '@mtasa/deprecated/radararea';
import {} from '@mtasa/deprecated/team';
import {} from '@mtasa/deprecated/vehicle';

import {} from '@mtasa/server/function/account';
import {} from '@mtasa/server/function/acl';
import {} from '@mtasa/server/function/admin';
import {} from '@mtasa/server/function/announcement';
import {} from '@mtasa/server/function/audio';
import {} from '@mtasa/server/function/blip';
import {} from '@mtasa/server/function/camera';
import {} from '@mtasa/server/function/clothes_and_body';
import {} from '@mtasa/server/function/collision_shape';
import {} from '@mtasa/server/function/cursor';
import {} from '@mtasa/server/function/element';
import {} from '@mtasa/server/function/event';
import {} from '@mtasa/server/function/explosion';
import {} from '@mtasa/server/function/file';
import {} from '@mtasa/server/function/input';
import {} from '@mtasa/server/function/map';
import {} from '@mtasa/server/function/marker';
import {} from '@mtasa/server/function/module';
import {} from '@mtasa/server/function/object';
import {} from '@mtasa/server/function/output';
import {} from '@mtasa/server/function/ped';
import {} from '@mtasa/server/function/pickup';
import {} from '@mtasa/server/function/player';
import {} from '@mtasa/server/function/projectile';
import {} from '@mtasa/server/function/radar_area';
import {} from '@mtasa/server/function/resource';
import {} from '@mtasa/server/function/server';
import {} from '@mtasa/server/function/settings_registry';
import {} from '@mtasa/server/function/sql';
import {} from '@mtasa/server/function/team';
import {} from '@mtasa/server/function/text';
import {} from '@mtasa/server/function/utility';
import {} from '@mtasa/server/function/vehicle';
import {} from '@mtasa/server/function/water';
import {} from '@mtasa/server/function/weapon';
import {} from '@mtasa/server/function/world';
import {} from '@mtasa/server/function/xml';

import {} from '@mtasa/server/oop/Account';
import {} from '@mtasa/server/oop/ACL';
import {} from '@mtasa/server/oop/ACLGroup';
import {} from '@mtasa/server/oop/Ban';
import {} from '@mtasa/server/oop/Blip';
import {} from '@mtasa/server/oop/ColShape';
import {} from '@mtasa/server/oop/Element';
import {} from '@mtasa/server/oop/File';
import {} from '@mtasa/server/oop/Marker';
import {} from '@mtasa/server/oop/Object';
import {} from '@mtasa/server/oop/Ped';
import {} from '@mtasa/server/oop/Player';
import {} from '@mtasa/server/oop/RadarArea';
import {} from '@mtasa/server/oop/Resource';
import {} from '@mtasa/server/oop/Team';
import {} from '@mtasa/server/oop/Timer';
import {} from '@mtasa/server/oop/Vehicle';
import {} from '@mtasa/server/oop/Water';
import {} from '@mtasa/server/oop/XML';
import {} from '@mtasa/server/oop/XmlNode';

import {} from '@mtasa/shared/utf8'